# Generated by Django 3.0.7 on 2021-05-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vuelodjango',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clase', models.CharField(max_length=30)),
                ('Servicio', models.CharField(max_length=10)),
                ('Comida', models.IntegerField()),
                ('Bebida', models.IntegerField()),
                ('Pelicula', models.IntegerField()),
                ('Subtotal', models.IntegerField()),
                ('Descuento', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
        ),
    ]
